# Generated by Django 4.1.7 on 2023-04-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('likes', models.IntegerField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=0)),
                ('value', models.IntegerField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('text', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('likes', models.IntegerField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Emoji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.emoji')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.post')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='post_emoji',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.user'),
        ),
        migrations.AddField(
            model_name='comm',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.user'),
        ),
        migrations.AddField(
            model_name='comm',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab6.post'),
        ),
    ]
