# Generated by Django 4.1.7 on 2023-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0002_comm_emoji_group_post_post_emoji_user_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
