# Generated by Django 4.1.7 on 2023-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=123, max_length=31, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comm',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
