# Generated by Django 4.1.7 on 2023-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0006_remove_user_date_of_birth_user_name_user_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_owner',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
