# Generated by Django 4.1.7 on 2023-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0007_user_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
